#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky10
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY1001"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval((indichash.containsKey("GZ10102"))
       && (indichash.containsKey("GZ20200")));
     
     eval( 
     ( (IndicFact)CommonUtil.getObj(indichash,"GZ10102")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ10102")).getLow_limit()
     && ( (IndicFact)CommonUtil.getObj(indichash,"GZ20200")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ20200")).getLow_limit()
     &&(
       (indichash.containsKey("JC10092"))&&( (IndicFact)CommonUtil.getObj(indichash,"JC10092")).getIndicval() >((IndicFact)CommonUtil.getObj(indichash,"JC10092")).getLow_limit()
     ||(indichash.containsKey("JC10069"))&&( (IndicFact)CommonUtil.getObj(indichash,"JC10069")).getIndicval() >((IndicFact)CommonUtil.getObj(indichash,"JC10069")).getLow_limit()
     ));
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1001",new Integer(1));

end


rule "KY1002"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval((indichash.containsKey("GZ10103"))
       && (indichash.containsKey("GZ20201")));
     eval( ( (IndicFact)CommonUtil.getObj(indichash,"GZ10103")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"GZ10103")).getLow_limit()
     && ( (IndicFact)CommonUtil.getObj(indichash,"GZ20201")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ20201")).getLow_limit()
      &&( 
        ((indichash.containsKey("JC10068"))&&( (IndicFact)CommonUtil.getObj(indichash,"JC10068")).getIndicval() >((IndicFact)CommonUtil.getObj(indichash,"JC10068")).getLow_limit())
     ||((indichash.containsKey("JC10070"))&&((IndicFact)CommonUtil.getObj(indichash,"JC10070")).getIndicval() >((IndicFact)CommonUtil.getObj(indichash,"JC10070")).getLow_limit()
     )
     )
     );
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1002",new Integer(1));

end
 