#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky16
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY1601"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval( (indichash.containsKey("GZ10082"))
					&&(indichash.containsKey("JC20064"))
					);
     eval( 
			     			((IndicFact)CommonUtil.getObj(indichash,"JC20064")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"JC20064")).getLow_limit()
			     &&(
								((indichash.containsKey("GZ20455"))&&
								((IndicFact)CommonUtil.getObj(indichash,"GZ20455")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"GZ20455")).getLow_limit()
								)
								||((indichash.containsKey("GZ20184"))&&
								((IndicFact)CommonUtil.getObj(indichash,"GZ20184")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ20184")).getLow_limit()
								)
								||((indichash.containsKey("GZ20446"))&&
								((IndicFact)CommonUtil.getObj(indichash,"GZ20446")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"GZ20446")).getLow_limit()
								)
			     	)
			     && ( (IndicFact)CommonUtil.getObj(indichash,"GZ10082")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"GZ10082")).getLow_limit()
     			);	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1601",new Integer(1));

end

rule "KY1602"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
       eval((indichash.containsKey("JC20066"))
       		&&(indichash.containsKey("GZ10083"))
       		 );
     eval(
     						((IndicFact)CommonUtil.getObj(indichash,"JC20066")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"JC20066")).getLow_limit()
     				&&(
     						((indichash.containsKey("GZ20456"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20456")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"GZ20456")).getLow_limit()
     						)
     						||((indichash.containsKey("GZ20185"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20185")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ20185")).getLow_limit()
     						)
     						||((indichash.containsKey("GZ20447"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20447")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"GZ20447")).getLow_limit()
     						)
     					)
						&&((IndicFact)CommonUtil.getObj(indichash,"GZ10083")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"GZ10083")).getLow_limit()
			);
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1602",new Integer(1));

end

rule "KY1603"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval((indichash.containsKey("JC20067"))
       	&& (indichash.containsKey("GZ10084")) 
       		);
     eval( 
     						((IndicFact)CommonUtil.getObj(indichash,"JC20067")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"JC20067")).getLow_limit()
     				&&(
     						((indichash.containsKey("GZ20457"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20457")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"GZ20457")).getLow_limit()
     						)
     						||((indichash.containsKey("GZ20186"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20186")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ20186")).getLow_limit()
     						)
     						||((indichash.containsKey("GZ20448"))&&
     						((IndicFact)CommonUtil.getObj(indichash,"GZ20448")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"GZ20448")).getLow_limit()
     						)
     					)
     				&&	((IndicFact)CommonUtil.getObj(indichash,"GZ10084")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ10084")).getLow_limit()
					);

	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1603",new Integer(1));

end 
rule "KY1604"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
   eval((indichash.containsKey("JC20068"))
      &&(indichash.containsKey("GZ10085"))
       );
     eval(
								((IndicFact)CommonUtil.getObj(indichash,"JC20068")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"JC20068")).getLow_limit()
     			&&(
     						((indichash.containsKey("GZ20458"))
     					&&((IndicFact)CommonUtil.getObj(indichash,"GZ20458")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"GZ20458")).getLow_limit()
     					)
     					||((indichash.containsKey("GZ20187"))
     					&&((IndicFact)CommonUtil.getObj(indichash,"GZ20187")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ20187")).getLow_limit()
     					)
     					||((indichash.containsKey("GZ20449"))
     					&&((IndicFact)CommonUtil.getObj(indichash,"GZ20449")).getIndicval()> ((IndicFact)CommonUtil.getObj(indichash,"GZ20449")).getLow_limit()
     					)
     				)
     			&& 		((IndicFact)CommonUtil.getObj(indichash,"GZ10085")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ10085")).getLow_limit()
     );
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1604",new Integer(1));

end 

rule "KY1605"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
   eval((indichash.containsKey("JC20069"))	);
     eval( 
     			((IndicFact)CommonUtil.getObj(indichash,"JC20069")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"JC20069")).getLow_limit()
		      );
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1605",new Integer(1));

end 


rule "KY1606"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
   eval((indichash.containsKey("JC20070"))	);
     eval( 
     			((IndicFact)CommonUtil.getObj(indichash,"JC20070")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"JC20070")).getLow_limit()
		      );
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1606",new Integer(1));

end 

rule "KY1607"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
   eval((indichash.containsKey("JC20071"))	);
     eval(
     			((IndicFact)CommonUtil.getObj(indichash,"JC20071")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"JC20071")).getLow_limit()
		      );

	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1607",new Integer(1));

end 

rule "KY1608"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
   eval((indichash.containsKey("JC20072"))	);
     eval( 
     			((IndicFact)CommonUtil.getObj(indichash,"JC20072")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"JC20072")).getLow_limit()
		      );
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1608",new Integer(1));

end 