#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky19
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY1901"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
     eval(indichash.containsKey("JC20300"));
     eval(((IndicFact)CommonUtil.getObj(indichash,"JC20300")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"JC20300")).getLow_limit());
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1901",new Integer(1));

end

rule "KY2008"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC11208"));
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY2008",new Integer(1));

end

rule "KY2009"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC11209"));
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY2009",new Integer(1));

end

rule "KY2010"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC11210"));
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY2010",new Integer(1));

end

rule "KY2011"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC11211"));
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY2011",new Integer(1));

end





















 