#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky11
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY1101"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash,propertyHash : propertyHash);
      eval((indichash.containsKey("JC10001"))
      &&(propertyHash.containsKey("SX1005")));
     eval( ( (IndicFact)CommonUtil.getObj(indichash,"JC10001")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"JC10001")).getLow_limit()
     );
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1101",new Integer(1));

end

rule "KY1102"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash,propertyHash : propertyHash);
      eval((indichash.containsKey("GZ30043"))
      &&(indichash.containsKey("JC10091"))
       &&(propertyHash.containsKey("SX1005"))
       && (indichash.containsKey("GZ10105")));
     eval( ( (IndicFact)CommonUtil.getObj(indichash,"GZ30043")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"GZ30043")).getLow_limit()
     && ( (IndicFact)CommonUtil.getObj(indichash,"GZ30043")).getIndicval() <= ((IndicFact)CommonUtil.getObj(indichash,"GZ30043")).getUpper_limit()
     && ( (IndicFact)CommonUtil.getObj(indichash,"JC10091")).getIndicval() > ((IndicFact)CommonUtil.getObj(indichash,"JC10091")).getLow_limit()
     && ( (IndicFact)CommonUtil.getObj(indichash,"GZ10105")).getIndicval() >=((IndicFact)CommonUtil.getObj(indichash,"GZ10105")).getLow_limit()
     );
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1102",new Integer(1));

end









 