#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky09
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY0901"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC10157"));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"JC10157")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"JC10157")).getLow_limit());
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY0901",new Integer(1));

end

rule "KY0902"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC10158"));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"JC10158")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"JC10158")).getLow_limit());
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY0902",new Integer(1));

end

rule "KY0903"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC10159"));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"JC10159")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"JC10159")).getLow_limit());
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY0903",new Integer(1));

end

rule "KY0904"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash);
      eval(indichash.containsKey("JC10160"));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"JC10160")).getIndicval() >= ((IndicFact)CommonUtil.getObj(indichash,"JC10160")).getLow_limit());
	
	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY0904",new Integer(1));

end




 