#created on: Jan 16, 2007
package com.ist.server.cal.aml.jrules.rules.aml_ky13
 
#list any import classes here.
import java.util.HashMap;
import java.lang.Boolean;

import com.ist.server.cal.aml.jrules.dto.RuleFact;
import com.ist.server.cal.aml.jrules.dto.IndicFact;
import com.ist.server.cal.aml.jrules.component.CommonUtil;

#declare any global variables here

 
rule "KY1301"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash,propertyHash : propertyHash);
     eval((propertyHash.containsKey("SX1004"))
     &&(indichash.containsKey("JC10163"))&&(indichash.containsKey("GZ10171")));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"GZ10171")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ10171")).getLow_limit()
     );

	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1301",new Integer(1));

end


rule "KY1302"
	when
	  #conditions
	  #get IndicFact from RuleFact.IndicHash
	  #get alertHash from RuleFact
      $T : RuleFact(alerthash : alertHash , indichash : indicHash,propertyHash : propertyHash);
     eval((propertyHash.containsKey("SX1004"))
     &&(indichash.containsKey("JC10164"))&&(indichash.containsKey("GZ10172")));
      eval( ( (IndicFact)CommonUtil.getObj(indichash,"GZ10172")).getIndicval()>=((IndicFact)CommonUtil.getObj(indichash,"GZ10172")).getLow_limit()
      );

	then
	#actions
	#set true(alert) into the alerthash
	  alerthash.put("KY1302",new Integer(1));

end
 

 
 
 
 
 
 
 
 
 
 
 
 